### PR TITLE
remove jinja templating delimiters from when statements, fixes #26

### LINKED ISSUE #26: Ansible warnings in 2.3.0
Hi Guys,

It seems latest ansible (since 2.3?) has changed the requirements for the when parameters:

 [WARNING]: when statements should not include jinja2 templating delimiters
such as {{ }} or {% %}. Found: {{ project_copy_previous_composer_vendors }}

Tested on 3.2.0 of f500.project_deploy

Not sure if the change for this would be backwards compatible?

### PR DESCRIPTION
**Pull request by zghosts**
Fixes the errors when running under ansible 2.3.*

### CODE REVIEW

**Comment by dincho** [comment]
Any reason this is not merged yet?

**Comment by jaspernbrouwer** [comment]
@ramondelafuente I'll leave merging up to you, so you can update Ansible Galaxy in one go 🙂

**Comment by ramondelafuente** [comment]
@dincho Because we fell asleep on the job, and apparently I'm still running Ansible 2.2  🙄 
@zghosts Thanks for the work 👍 

@jaspernbrouwer I confirmed that this works as far back as Ansible 2.0.

**Comment by ramondelafuente** [comment]
Role version is now `v3.2.2`

**Comment by zghosts** [comment]
You're very welcome

**Comment by dincho** [comment]
Thank you guys!

**Pull request merged**
