### PR TITLE
better implementation of deploy hooks

### PR DESCRIPTION
**Pull request by dincho**
After updating to ansible 2, for some reason the hack used in the deploy hooks stopped working for me.

This PR propose hackless implementation of deploy hooks based on [ansible conditionals](http://docs.ansible.com/ansible/playbooks_conditionals.html).

As the temporary workaround until this is merged one can use:
```
    empty_deploy_hooks: "{{ playbook_dir }}/deploy_hooks/empty.yml"
    project_deploy_hook_on_initialize: "{{ empty_deploy_hooks }}"
    project_deploy_hook_on_update_source: "{{ empty_deploy_hooks }}"
    project_deploy_hook_on_create_build_dir: "{{ empty_deploy_hooks }}"
    project_deploy_hook_on_perform_build: "{{ empty_deploy_hooks }}"
    project_deploy_hook_on_make_shared_resources: "{{ empty_deploy_hooks }}"
    project_deploy_hook_on_finalize: "{{ empty_deploy_hooks }}"
```

### CODE REVIEW

**Comment by ramondelafuente** [comment]
Are you sure this works? The conditionals _always_ include a file, and add a "when" to every task inside. Meaning you'll get the same error if the file does not exist.

The reason this is breaking is because Ansible now runs the lookup plugin in the playbook folder instead of the role folder as far as I can tell.

But your solution does lead me to believe we can start using the {{ playbook_dir }} variable in de `default` method...

**Comment by dincho** [comment]
> Are you sure this (the proposed solution, not the workaround) works? The conditionals always include a file, and add a "when" to every task inside. Meaning you'll get the same error if the file does not exist.

Well, at least it works in my environment with ansible 2.0.0.2. Please see [example output](http://pastebin.com/BVjNhxb1) the hooks tasks seems to be skipped.

Maybe this is BC change and would not work with older ansible versions?

> But your solution does lead me to believe we can start using the {{ playbook_dir }} variable in de default method...

I don't see how it can be used, because it's playbook dir, you need role dir.

**Comment by dincho** [comment]
Yep looks like it's BC break:

```
[dincho@macbook]-[~/Projects/xxx/ansible]$ ansible --version
ansible 1.9.4
  configured module search path = None
[dincho@macbook]-[~/Projects/xxx/ansible]$ ansible-playbook -u xxx -i inventory/prod.ini deploy.yml
# github.com:22 SSH-2.0-libssh-0.7.0
ERROR: file could not read: /Users/dincho/Projects/xxx/ansible/roles/f500.project_deploy/tasks/{{ project_deploy_hook_on_initialize }}
```

Any ideas how to solve this? I don't mind using ansible v1, but our CI is using ansible v2, so I need to fix this somehow.

**Comment by ramondelafuente** [comment]
I don;t mind the BC break, I'll merge and release a new major for this role. The fix is great, because the hack is no longer needed :-)
[it took me quite a while to come up with it in the first place]

**Comment by dincho** [comment]
@ramondelafuente I just prepared new PR which just fix the hack, it uses ```role_path``` ansible variable. Please let me know if you want me to open it. Please see: https://github.com/dincho/ansible-project_deploy/commit/4c42e90a5762c398c09a64b7861d5d3da4b827fb

docs: http://docs.ansible.com/ansible/playbooks_variables.html#magic-variables-and-how-to-access-information-about-other-hosts

**Comment by ramondelafuente** [comment]
I have already merged and released v3.0.0 in galaxy. This should solve your problem, I think?

**Comment by dincho** [comment]
> I have already merged and released v3.0.0 in galaxy. This should solve your problem, I think?

Yes it did. Thank you for the fast release.

Still if you need the BC fix, please let me know.

**Comment by ramondelafuente** [comment]
Thanks for taking to the time to fix this, very much obliged.

**Pull request merged**
